#!/bin/sh

set -eux

if [ -z "$(ls -A /var/lib/postgresql)" ]; then
    su-exec postgres initdb -E UTF8 -U app

    cat >> /var/lib/postgresql/postgresql.conf << EOF
listen_addresses='*'
EOF

    cat > /var/lib/postgresql/pg_hba.conf << EOF
local   all             all                                     trust
host    all             all             ::1/128                 md5
host    all             all             127.0.0.0/8             md5
host    all             all             10.0.0.0/8              md5
host    all             all             172.16.0.0/12           md5
host    all             all             192.168.0.0/16          md5
EOF

    cat << EOF | su-exec postgres postgres --single postgres
CREATE DATABASE app ENCODING 'UTF8';
ALTER USER app WITH PASSWORD '$PGPASS';
EOF

    if [ -d /init/postgres ]; then
        su-exec postgres pg_ctl -o "-c listen_addresses='localhost'" -w start

        for file in $(find /init/postgres -type f -name '*.sql' | sort); do
            su-exec postgres psql -U app -f "$file" app
        done

        su-exec postgres pg_ctl -m fast -w stop
    fi
else
    find /var/lib/postgresql -type d -exec chmod 700 {} \;
    find /var/lib/postgresql -type f -exec chmod 600 {} \;
fi
