#!/bin/bash

set -euxo pipefail

if [ "${XDEBUG_ENABLED}" = "1" ]; then
    ln -s ../../mods-available/xdebug.ini /etc/php/7.4/cli/conf.d/20-xdebug.ini
    ln -s ../../mods-available/xdebug.ini /etc/php/7.4/fpm/conf.d/20-xdebug.ini
else
    rm -f /etc/php/7.4/cli/conf.d/20-xdebug.ini /etc/php/7.4/fpm/conf.d/20-xdebug.ini || true
fi
