version: "3.7"
volumes:
  data: {}
services:
  jenkins:
    image: akilli/jenkins
    restart: unless-stopped
    ports:
      - "80:8080"
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
