FROM akilli/docker
LABEL maintainer="Ayhan Akilli"

ENV GITEA_TOKEN=
ENV GITEA_URL=
ENV RUNNER_LABELS=
ENV RUNNER_NAME=runner

RUN wget -O /usr/local/bin/gitea-runner https://gitea.com/gitea/act_runner/releases/download/v0.1.8/act_runner-0.1.8-linux-amd64 && \
    chmod a+x /usr/local/bin/gitea-runner && \
    app-user && \
    app-chown
COPY runner /usr/local/bin/runner

CMD ["su-exec", "app", "runner"]
