FROM akilli/docker
LABEL maintainer="Ayhan Akilli"

ENV GITEA_TOKEN=
ENV GITEA_URL=
ENV RUNNER_LABELS=alpine,alpine-edge,docker
ENV RUNNER_NAME=runner

RUN wget -O /usr/local/bin/gitea-runner https://dl.gitea.com/act_runner/main/act_runner-main-linux-amd64 && \
    chmod a+x /usr/local/bin/gitea-runner && \
    app-user && \
    app-chown
COPY runner /usr/local/bin/runner

CMD ["su-exec", "app", "runner"]
