FROM akilli/base
LABEL maintainer="Ayhan Akilli"

RUN apk add --no-cache \
        docker-cli \
        docker-cli-buildx \
        docker-cli-compose && \
    app-user && \
    app-chown
COPY init/ /init/
