#!/bin/sh

set -eux

if [ -S "/var/run/docker.sock" ]; then
    _hostId=$(stat -c %g /var/run/docker.sock)
    _localId=$(getent group docker | cut -d: -f3 || true)
    _inGroup=$(id -nG app | tr ' ' '\n' | grep '^docker$' || true)

    if [ "$_hostId" = "$_localId" ] && [ "$_inGroup" = "docker" ]; then
        exit 0
    fi

    if [ -n "$_localId" ]; then
        delgroup docker
    fi

    addgroup -S -g $_hostId docker
    addgroup app docker
fi
