#!/bin/sh

set -eux

groupId=$(stat -c "%g" /var/run/docker.sock)
groupName=$(stat -c "%G" /var/run/docker.sock)

if [ groupId != "1000" ] && [ groupName != "docker" ]; then
    app-user
    app-chown
    addgroup --gid $groupId --system docker
    addgroup app docker
fi
