#!/bin/bash

_opt="-t ${IMAGE_NAME}"

if [ -n "$DOCKERFILE_PATH" ]; then
    _opt="${_opt} -f ${DOCKERFILE_PATH}"
fi

if [ "$DOCKER_TAG" == "next" ]; then
    _opt="${_opt} --build-arg TAR=https://downloads.php.net/~carusogabriel/php-8.0.0alpha2.tar.xz"
fi

echo "docker build ${_opt} ."
docker build ${_opt} .
