FROM akilli/base
LABEL maintainer="Ayhan Akilli"

ENV DRONE_PLATFORM_ARCH=amd64
ENV DRONE_PLATFORM_OS=linux
ENV GODEBUG="netdns=go"

RUN apk add --no-cache \
    docker-cli \
    docker-cli-buildx \
    docker-cli-compose \
    git \
    sudo && \
    echo 'app ALL = NOPASSWD: /usr/bin/docker' >> /etc/sudoers && \
    wget https://github.com/drone-runners/drone-runner-exec/releases/latest/download/drone_runner_exec_linux_amd64.tar.gz && \
    tar -xf drone_runner_exec_linux_amd64.tar.gz && \
    chmod a+x drone-runner-exec && \
    mv drone-runner-exec /usr/local/bin/drone-runner-exec && \
    rm drone_runner_exec_linux_amd64.tar.gz && \
    app-user && \
    app-chown

CMD ["su-exec", "app", "drone-runner-exec"]
