FROM akilli/base
LABEL maintainer="Ayhan Akilli"

ENV JAVA_HOME=/usr/lib/jvm/default-jvm
ENV JENKINS_GROUP=app
ENV JENKINS_HOME=/data
ENV JENKINS_USER=app

RUN apk add --no-cache \
        docker-cli \
        docker-cli-buildx \
        docker-cli-compose \
        git \
        openjdk11-jre \
        sudo \
        ttf-dejavu && \
    apk add --no-cache --virtual .build \
        binutils \
        openjdk11-jdk && \
    jlink \
        --add-modules ALL-MODULE-PATH \
        --strip-debug \
        --no-man-pages \
        --no-header-files \
        --compress=2 \
        --output /tmp/default-jvm && \
    rm -rf /usr/lib/jvm/* && \
    mv /tmp/default-jvm $JAVA_HOME && \
    apk del .build && \
    echo 'app ALL = NOPASSWD: /usr/bin/docker' >> /etc/sudoers && \
    mkdir -p /var/cache/jenkins && \
    chown -R app:app /var/cache/jenkins && \
    wget -O /app/jenkins.war https://updates.jenkins-ci.org/latest/jenkins.war && \
    app-user && \
    app-chown

CMD ["su-exec", "app", "java", "-Djava.awt.headless=true", "-jar", "/app/jenkins.war", "--webroot=/var/cache/jenkins"]
