config.local-keys = [
    "authentication.fallback-admin.*",
    "certificate.*",
    "cluster.*",
    "config.local-keys.*",
    "directory.*",
    "http.*",
    "!server.blocked-ip.*",
    "!server.allowed-ip.*",
    "server.*",
    "storage.*",
    "store.*",
    "tracer.*"
]

server.hostname = "%{env:STALWART_HOST}%"
http.hsts = true
http.permissive-cors = false
http.use-x-forwarded = true

certificate.default.default = true
certificate.default.cert = "%{file:/ssl/app.crt}%"
certificate.default.private-key = "%{file:/ssl/app.key}%"

authentication.fallback-admin.user = "admin"
authentication.fallback-admin.secret = "%{env:STALWART_PASSWORD}%"

storage.data = "rocksdb"
storage.fts = "rocksdb"
storage.blob = "rocksdb"
storage.lookup = "rocksdb"
storage.directory = "internal"
storage.search-index.default-language = "de"

store.rocksdb.type = "rocksdb"
store.rocksdb.path = "/data"
store.rocksdb.compression = "lz4"
store.rocksdb.purge.frequency = "0 3 *"

directory.internal.type = "internal"
directory.internal.store = "rocksdb"

tracer.console.enable = true
tracer.console.type = "console"
tracer.console.level = "info"
tracer.console.ansi = false

server.listener.http.bind = "[::]:8080"
server.listener.http.protocol = "http"

server.listener.https.bind = "[::]:443"
server.listener.https.protocol = "http"
server.listener.https.tls.implicit = true

server.listener.imaptls.bind = "[::]:993"
server.listener.imaptls.protocol = "imap"
server.listener.imaptls.tls.implicit = true

server.listener.smtp.bind = "[::]:25"
server.listener.smtp.protocol = "smtp"

server.listener.submissions.bind = "[::]:465"
server.listener.submissions.protocol = "smtp"
server.listener.submissions.tls.implicit = true

server.auto-ban.auth.rate = "100/1d"
server.auto-ban.abuse.rate = "35/1d"
server.auto-ban.loiter.rate = "150/1d"
server.auto-ban.scan.rate = "150/1d"
