FROM akilli/base
LABEL maintainer="Ayhan Akilli"

ENV STALWART_HOST=mail.example.com
ENV STALWART_PASSWORD=admin

RUN apk add --no-cache \
        rocksdb \
        stalwart-cli \
        stalwart-mail && \
    app-user && \
    app-chown
COPY config.toml /app/config.toml

CMD ["su-exec", "app", "stalwart", "--config", "/app/config.toml"]
