FROM akilli/base
LABEL maintainer="Ayhan Akilli"

ENV DEV=0

RUN apk add --no-cache \
        icu-data-full \
        php85 \
        php85-bz2 \
        php85-ctype \
        php85-curl \
        php85-dom \
        php85-fileinfo \
        php85-fpm \
        php85-ftp \
        php85-gd \
        php85-iconv \
        php85-intl \
        php85-ldap \
        php85-mbstring \
        php85-mysqlnd \
        php85-openssl \
        php85-pdo \
        php85-pdo_mysql \
        php85-pdo_pgsql \
        php85-pdo_sqlite \
        php85-pgsql \
        php85-phar \
        php85-posix \
        php85-session \
        php85-simplexml \
        php85-soap \
        php85-sockets \
        php85-sodium \
        php85-sqlite3 \
        php85-tokenizer \
        php85-xml \
        php85-xmlreader \
        php85-xmlwriter \
        php85-xsl \
        php85-zip && \
    ln -s php85 /etc/php && \
    (which php || ln -s php85 /usr/bin/php) && \
    ln -s php-fpm85 /usr/sbin/php-fpm && \
    rm -f \
        /etc/php/php-fpm.d/www.conf \
        /etc/php/php-fpm.conf && \
    app-user && \
    app-chown
COPY etc/ /etc/php/
COPY init/ /init/

CMD ["php-fpm"]
