FROM akilli/base
LABEL maintainer="Ayhan Akilli"

ENV DEV=0

RUN apk add --no-cache \
        icu-data-full \
        php83 \
        php83-bz2 \
        php83-ctype \
        php83-curl \
        php83-dom \
        php83-fileinfo \
        php83-fpm \
        php83-ftp \
        php83-gd \
        php83-iconv \
        php83-intl \
        php83-json \
        php83-ldap \
        php83-mbstring \
        php83-mysqlnd \
        php83-opcache \
        php83-openssl \
        php83-pdo \
        php83-pdo_mysql \
        php83-pdo_pgsql \
        php83-pdo_sqlite \
        php83-pgsql \
        php83-phar \
        php83-posix \
        php83-session \
        php83-simplexml \
        php83-soap \
        php83-sockets \
        php83-sodium \
        php83-sqlite3 \
        php83-tokenizer \
        php83-xml \
        php83-xmlreader \
        php83-xmlwriter \
        php83-xsl \
        php83-zip && \
    ln -s php83 /etc/php && \
    (which php || ln -s php83 /usr/bin/php) && \
    ln -s php-fpm83 /usr/sbin/php-fpm && \
    rm -f \
        /etc/php/php-fpm.d/www.conf \
        /etc/php/php-fpm.conf && \
    app-user && \
    app-chown
COPY etc/ /etc/php/
COPY init/ /init/

CMD ["php-fpm"]
