FROM akilli/base
LABEL maintainer="Ayhan Akilli"

ENV DEV=0

RUN apk add --no-cache \
        fcgi \
        icu-data-full \
        php84 \
        php84-bz2 \
        php84-ctype \
        php84-curl \
        php84-dom \
        php84-fileinfo \
        php84-fpm \
        php84-ftp \
        php84-gd \
        php84-iconv \
        php84-intl \
        php84-json \
        php84-ldap \
        php84-mbstring \
        php84-mysqlnd \
        php84-opcache \
        php84-openssl \
        php84-pdo \
        php84-pdo_mysql \
        php84-pdo_pgsql \
        php84-pdo_sqlite \
        php84-pgsql \
        php84-phar \
        php84-posix \
        php84-session \
        php84-simplexml \
        php84-soap \
        php84-sockets \
        php84-sodium \
        php84-sqlite3 \
        php84-tokenizer \
        php84-xml \
        php84-xmlreader \
        php84-xmlwriter \
        php84-xsl \
        php84-zip && \
    ln -s php84 /etc/php && \
    (which php || ln -s php84 /usr/bin/php) && \
    ln -s php-fpm84 /usr/sbin/php-fpm && \
    rm -f \
        /etc/php/php-fpm.d/www.conf \
        /etc/php/php-fpm.conf && \
    app-user && \
    app-chown
COPY etc/ /etc/php/
COPY init/ /init/

CMD ["php-fpm"]

HEALTHCHECK CMD SCRIPT_NAME=/status SCRIPT_FILENAME=/status REQUEST_METHOD=GET cgi-fcgi -bind -connect 127.0.0.1:9000 || exit 1
