FROM akilli/base
LABEL maintainer="Ayhan Akilli"

ENV GOGS_CUSTOM=/data
ENV GOGS_USER=app
ENV GOGS_WORK_DIR=/app

RUN apk add --no-cache gogs && \
    rm -rf \
        /etc/gogs \
        /var/lib/gogs && \
    app-user && \
    app-chown
COPY app.ini /data/conf/app.ini

CMD ["su-exec", "app", "gogs", "web"]

HEALTHCHECK CMD wget -O /dev/null -q http://0.0.0.0/healthcheck || exit 1
