name: dockerhub
on:
  workflow_call:
    inputs:
      image:
        type: string
        required: false
        default: ${{ github.repository }}
      tag:
        type: string
        required: false
        default: latest
      context:
        type: string
        required: false
        default: "{{defaultContext}}"
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        uses: docker/setup-buildx-action@v2
      - name: login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build & load
        uses: docker/build-push-action@v3
        with:
          load: true
          tags: ${{ inputs.image }}:${{ inputs.tag }}
          context: ${{ inputs.context }}
      - name: test
        run: |
          docker run --rm --entrypoint ls ${{ inputs.image }}:${{ inputs.tag }} -al
      - name: build & push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ inputs.image }}:${{ inputs.tag }}
          context: ${{ inputs.context }}
