name: dockerhub
on:
  workflow_call:
    inputs:
      image:
        type: string
        required: false
        default: ${{ github.repository }}
      context:
        type: string
        required: false
        default: "{{defaultContext}}"
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: meta
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: ${{ inputs.image }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - name: setup
        uses: docker/setup-buildx-action@v2
      - name: login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build & load
        uses: docker/build-push-action@v4
        with:
          load: true
          tags: ${{ inputs.image }}:test
          context: ${{ inputs.context }}
      - name: test
        run: docker run --rm --entrypoint ls ${{ inputs.image }}:test -al
      - name: build & push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          context: ${{ inputs.context }}
