name: release
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - ".github/**"
      - "**/*.md"
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      base: ${{ steps.filter.outputs.base }}
      docker: ${{ steps.filter.outputs.docker }}
      gitea: ${{ steps.filter.outputs.gitea }}
      gitea-runner: ${{ steps.filter.outputs.gitea-runner }}
      go: ${{ steps.filter.outputs.go }}
      gogs: ${{ steps.filter.outputs.gogs }}
      jenkins: ${{ steps.filter.outputs.jenkins }}
      maildev: ${{ steps.filter.outputs.maildev }}
      mysql: ${{ steps.filter.outputs.mysql }}
      nginx: ${{ steps.filter.outputs.nginx }}
      node: ${{ steps.filter.outputs.node }}
      php: ${{ steps.filter.outputs.php }}
      postgres: ${{ steps.filter.outputs.postgres }}
      redis: ${{ steps.filter.outputs.redis }}
      registry: ${{ steps.filter.outputs.registry }}
      traefik: ${{ steps.filter.outputs.traefik }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: detect changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            base:
              - 'base/**'
            docker:
              - 'docker/**'
            gitea:
              - 'gitea/**'
            gitea-runner:
              - 'gitea-runner/**'
            go:
              - 'go/**'
            gogs:
              - 'gogs/**'
            jenkins:
              - 'jenkins/**'
            maildev:
              - 'maildev/**'
            mysql:
              - 'mysql/**'
            nginx:
              - 'nginx/**'
            node:
              - 'node/**'
            php:
              - 'php/**'
            postgres:
              - 'postgres/**'
            redis:
              - 'redis/**'
            registry:
              - 'registry/**'
            traefik:
              - 'traefik/**'
  base:
    needs: changes
    if: needs.changes.outputs.base == 'true'
    uses: akilli/docker/.github/workflows/dockerhub.yml@master
    with:
      image: akilli/base
      context: "{{defaultContext}}:base"
    secrets: inherit
  docker:
    needs: [changes, base]
    if: (success() && needs.changes.outputs.base == 'true') || (always() && needs.changes.outputs.docker == 'true')
    uses: akilli/docker/.github/workflows/dockerhub.yml@master
    with:
      image: akilli/docker
      context: "{{defaultContext}}:docker"
    secrets: inherit
  gitea:
    needs: [changes, base]
    if: (success() && needs.changes.outputs.base == 'true') || (always() && needs.changes.outputs.gitea == 'true')
    uses: akilli/docker/.github/workflows/dockerhub.yml@master
    with:
      image: akilli/gitea
      context: "{{defaultContext}}:gitea"
    secrets: inherit
  gitea-runner:
    needs: [changes, docker]
    if: (success() && needs.changes.outputs.docker == 'true') || (always() && needs.changes.outputs.gitea-runner == 'true')
    uses: akilli/docker/.github/workflows/dockerhub.yml@master
    with:
      image: akilli/gitea-runner
      context: "{{defaultContext}}:gitea-runner"
    secrets: inherit
  go:
    needs: [changes, base]
    if: (success() && needs.changes.outputs.base == 'true') || (always() && needs.changes.outputs.go == 'true')
    uses: akilli/docker/.github/workflows/dockerhub.yml@master
    with:
      image: akilli/go
      context: "{{defaultContext}}:go"
    secrets: inherit
  gogs:
    needs: [changes, base]
    if: (success() && needs.changes.outputs.base == 'true') || (always() && needs.changes.outputs.gogs == 'true')
    uses: akilli/docker/.github/workflows/dockerhub.yml@master
    with:
      image: akilli/gogs
      context: "{{defaultContext}}:gogs"
    secrets: inherit
  jenkins:
    needs: [changes, docker]
    if: (success() && needs.changes.outputs.docker == 'true') || (always() && needs.changes.outputs.jenkins == 'true')
    uses: akilli/docker/.github/workflows/dockerhub.yml@master
    with:
      image: akilli/jenkins
      context: "{{defaultContext}}:jenkins"
    secrets: inherit
  maildev:
    needs: [changes, node]
    if: (success() && needs.changes.outputs.node == 'true') || (always() && needs.changes.outputs.maildev == 'true')
    uses: akilli/docker/.github/workflows/dockerhub.yml@master
    with:
      image: akilli/maildev
      context: "{{defaultContext}}:maildev"
    secrets: inherit
  mysql:
    needs: [ changes, base ]
    if: (success() && needs.changes.outputs.base == 'true') || (always() && needs.changes.outputs.mysql == 'true')
    uses: akilli/docker/.github/workflows/dockerhub.yml@master
    with:
      image: akilli/mysql
      context: "{{defaultContext}}:mysql"
    secrets: inherit
  nginx:
    needs: [changes, base]
    if: (success() && needs.changes.outputs.base == 'true') || (always() && needs.changes.outputs.nginx == 'true')
    uses: akilli/docker/.github/workflows/dockerhub.yml@master
    with:
      image: akilli/nginx
      context: "{{defaultContext}}:nginx"
    secrets: inherit
  node:
    needs: [changes, base]
    if: (success() && needs.changes.outputs.base == 'true') || (always() && needs.changes.outputs.node == 'true')
    uses: akilli/docker/.github/workflows/dockerhub.yml@master
    with:
      image: akilli/node
      context: "{{defaultContext}}:node"
    secrets: inherit
  php:
    needs: [changes, base]
    if: (success() && needs.changes.outputs.base == 'true') || (always() && needs.changes.outputs.php == 'true')
    uses: akilli/docker/.github/workflows/dockerhub.yml@master
    with:
      image: akilli/php
      context: "{{defaultContext}}:php"
    secrets: inherit
  postgres:
    needs: [changes, base]
    if: (success() && needs.changes.outputs.base == 'true') || (always() && needs.changes.outputs.postgres == 'true')
    uses: akilli/docker/.github/workflows/dockerhub.yml@master
    with:
      image: akilli/postgres
      context: "{{defaultContext}}:postgres"
    secrets: inherit
  redis:
    needs: [changes, base]
    if: (success() && needs.changes.outputs.base == 'true') || (always() && needs.changes.outputs.redis == 'true')
    uses: akilli/docker/.github/workflows/dockerhub.yml@master
    with:
      image: akilli/redis
      context: "{{defaultContext}}:redis"
    secrets: inherit
  registry:
    needs: [changes, base]
    if: (success() && needs.changes.outputs.base == 'true') || (always() && needs.changes.outputs.registry == 'true')
    uses: akilli/docker/.github/workflows/dockerhub.yml@master
    with:
      image: akilli/registry
      context: "{{defaultContext}}:registry"
    secrets: inherit
  traefik:
    needs: [changes, base]
    if: (success() && needs.changes.outputs.base == 'true') || (always() && needs.changes.outputs.traefik == 'true')
    uses: akilli/docker/.github/workflows/dockerhub.yml@master
    with:
      image: akilli/traefik
      context: "{{defaultContext}}:traefik"
    secrets: inherit
