name: release
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - ".github/**"
      - "**/*.md"
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      base: ${{ steps.filter.outputs.base }}
      jenkins: ${{ steps.filter.outputs.jenkins }}
      nginx: ${{ steps.filter.outputs.nginx }}
      node: ${{ steps.filter.outputs.node }}
      php: ${{ steps.filter.outputs.php }}
      postgres: ${{ steps.filter.outputs.postgres }}
      registry: ${{ steps.filter.outputs.registry }}
      traefik: ${{ steps.filter.outputs.traefik }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: detect changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            base:
              - 'base/**'
            jenkins:
              - 'jenkins/**'
            nginx:
              - 'nginx/**'
            node:
              - 'node/**'
            php:
              - 'php/**'
            postgres:
              - 'postgres/**'
            registry:
              - 'registry/**'
            traefik:
              - 'traefik/**'
  base:
    needs: changes
    if: needs.changes.outputs.base == 'true'
    uses: akilli/docker/.github/workflows/dockerhub.yml@master
    with:
      image: akilli/base
      context: "{{defaultContext}}:base"
    secrets: inherit
  jenkins:
    needs: [changes, base]
    if: (success() && needs.base.if == 'true') || (always() && needs.changes.outputs.jenkins == 'true')
    uses: akilli/docker/.github/workflows/dockerhub.yml@master
    with:
      image: akilli/jenkins
      context: "{{defaultContext}}:jenkins"
    secrets: inherit
  nginx:
    needs: [changes, base]
    if: (success() && needs.base.if == 'true') || (always() && needs.changes.outputs.nginx == 'true')
    uses: akilli/docker/.github/workflows/dockerhub.yml@master
    with:
      image: akilli/nginx
      context: "{{defaultContext}}:nginx"
    secrets: inherit
  node:
    needs: [changes, base]
    if: (success() && needs.base.if == 'true') || (always() && needs.changes.outputs.node == 'true')
    uses: akilli/docker/.github/workflows/dockerhub.yml@master
    with:
      image: akilli/node
      context: "{{defaultContext}}:node"
    secrets: inherit
  php:
    needs: [changes, base]
    if: (success() && needs.base.if == 'true') || (always() && needs.changes.outputs.php == 'true')
    uses: akilli/docker/.github/workflows/dockerhub.yml@master
    with:
      image: akilli/php
      context: "{{defaultContext}}:php"
    secrets: inherit
  postgres:
    needs: [changes, base]
    if: (success() && needs.base.if == 'true') || (always() && needs.changes.outputs.postgres == 'true')
    uses: akilli/docker/.github/workflows/dockerhub.yml@master
    with:
      image: akilli/postgres
      context: "{{defaultContext}}:postgres"
    secrets: inherit
  registry:
    needs: [changes, base]
    if: (success() && needs.base.if == 'true') || (always() && needs.changes.outputs.registry == 'true')
    uses: akilli/docker/.github/workflows/dockerhub.yml@master
    with:
      image: akilli/registry
      context: "{{defaultContext}}:registry"
    secrets: inherit
  traefik:
    needs: [changes, base]
    if: (success() && needs.base.if == 'true') || (always() && needs.changes.outputs.traefik == 'true')
    uses: akilli/docker/.github/workflows/dockerhub.yml@master
    with:
      image: akilli/traefik
      context: "{{defaultContext}}:traefik"
    secrets: inherit
